---
title: Remove 'Troubleshooting Compatibility' from Context Menu
description: Removes 'Troubleshooting Compatibility' from context menu
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked'; Value = '{1d27f844-3a1f-4410-85ac-14651078412d}'; Data = ''; Type = 'REG_SZ' },
        @{ Path = 'HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked'; Value = '{1d27f844-3a1f-4410-85ac-14651078412d}'; Data = ''; Type = 'REG_SZ' }
      )
    wait: true
