---
title: AppX
description: Removes AppX packages and prevents them from being reinstalled
onUpgrade: false
actions:
  - !writeStatus: {status: 'Removing AppX packages'}
  
  # The reason of removing those applications is that they might be sending user data,
  # showing unwanted content and using hardware resources. They can also simply be annoyances
  # that are never used. However, most of these applications can be reinstalled via
  # Microsoft Store in case the user needs them.

  # https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10

  #####################################################################################################

  # Get current AppX packages to deprovision removed ones afterward
  - !powerShell:
    command: |
      (Get-AppxPackage).PackageFamilyName |
        Out-File """$([Environment]::GetFolderPath('Windows'))\AtlasModules\AtlasPackagesOld.txt"""
    runas: currentUserElevated
    wait: true

  # AppX Microsoft Teams
  # Seems legacy - not in 23H2
  - !taskKill: {name: 'msteams*', ignoreErrors: true}
  - !appx: {name: 'MicrosoftTeams*', type: family}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Communications', value: 'ConfigureChatAutoInstall', data: '0', type: REG_DWORD}

  # New AppX Teams in 24H2
  - !taskKill: {name: 'ms-teams*', ignoreErrors: true}
  - !appx: {name: 'MSTeams*', type: family}
  # 24H2 Copilot app
  - !appx: {name: 'Microsoft.Copilot*', type: family}
  - !powerShell:
     wait: true
     exeDir: true
     errorAction: Ignore
     weight: 48
     command: >-
       .\REMOVEAPPX.ps1 -Packages @(
         'Clipchamp.Clipchamp*'
         'Disney.37853FC22B2CE*'
         'SpotifyAB.SpotifyMusic*'
         'Microsoft.549981C3F5F10*'
         'Microsoft.XboxApp*'
         'microsoft.windowscommunicationsapps*'
         'Microsoft.MSPaint*'
         'Microsoft.Getstarted*'
         'Microsoft.ZuneVideo*'
         'MicrosoftCorporationII.MicrosoftFamily*'
         'Microsoft.MixedReality.Portal*'
         'Microsoft.Windows.DevHome*'
         'Microsoft.BingWeather*'
         'Microsoft.BingSearch*'
         'Microsoft.OutlookForWindows*'
         'Microsoft.GetHelp*'
         'Microsoft.MicrosoftOfficeHub*'
         'Microsoft.Microsoft3DViewer*'
         'Microsoft.MicrosoftSolitaireCollection*'
         'Microsoft.MicrosoftStickyNotes*'
         'Microsoft.Office.OneNote*'
         'Microsoft.People*'
         'Microsoft.PowerAutomateDesktop*'
         'Microsoft.ScreenSketch*'
         'Microsoft.SkypeApp*'
         'Microsoft.Todos*'
         'Microsoft.WindowsAlarms*'
         'Microsoft.WindowsCamera*'
         'Microsoft.WindowsFeedbackHub*'
         'Microsoft.WindowsMaps*'
         'Microsoft.WindowsSoundRecorder*'
         'Ink.Handwriting.Main.Store.en-US1.0'
         'Microsoft.BingNews*'
         'Microsoft.YourPhone*'
       )
      
  - !powerShell:
    command: |
      Get-AppxPackage Microsoft.YourPhone* | Remove-AppxPackage
      Get-AppxProvisionedPackage -Online | Where-Object { $_.DisplayName -eq 'Microsoft.YourPhone' } | Remove-AppxProvisionedPackage -Online
    runas: currentUserElevated
    wait: true

  # Prevent provisioned applications from being reinstalled
  # https://learn.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update
  - !powerShell:
    command: |
      $a = """$([Environment]::GetFolderPath('Windows'))\AtlasModules\AtlasPackagesOld.txt"""
      (diff (gc $a) ((Get-AppxPackage).PackageFamilyName)).InputObject | 
        Foreach-Object { New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned" -Name $_ -Force };
      Remove-Item $a -Force
    runas: currentUserElevated
    wait: true

  # Clear caches of Client.CBS and more
  # Start menu cache is cleared later
  - !writeStatus: {status: 'Clearing AppX caches'}
  - !appx: {operation: clearCache, name: '*MicrosoftWindows.Client.CBS*'}
  - !appx: {operation: clearCache, name: '*Microsoft.Windows.Search*'}
  - !appx: {operation: clearCache, name: '*Microsoft.Windows.SecHealthUI*'}
