---
title: Defaults
description: Run default AtlasFolder scripts
actions:
  - !writeStatus: {status: 'Applying default Atlas Folder settings'}
  - !cmd:
    command: 'cmd /c "reg import .\DEFAULT.reg > nul 2>&1"'
    exeDir: true
    wait: true
    onUpgrade: false
    runas: currentUserElevated
  # this being commented is normal
  # I felt that it created more problems than it actually solves any.
  # and since we are rewriting a bunch of the playbook in powershell, this isn't really needed for the time being
  # should have an automated function which changes the paths in the registry when the script moves places
  #
  # - !powerShell:
  #   command: '.\DEFAULT.ps1'
  #   exeDir: true
  #   onUpgrade: true
  #   wait: true
  #   runas: currentUserElevated
