---
title: Defaults
description: Run default AtlasFolder scripts
actions:
  - !writeStatus: {status: 'Applying default Atlas Folder settings'}
  - !cmd:
    command: 'cmd /c "reg import .\DEFAULT.reg > nul 2>&1"'
    exeDir: true
    wait: true
    onUpgrade: false
    runas: currentUserElevated
  - !powerShell:
    command: '.\DEFAULT.ps1'
    exeDir: true
    onUpgrade: true
    wait: true
    runas: currentUserElevated
