---
title: Reverts changes
description: Reverts changes from past versions
privilege: TrustedInstaller
onUpgrade: true
actions:
  - !writeStatus: {status: "Reverting old changes"}
  - !appx: {name: 'Microsoft.GamingServices*', type: family}
  - !powerShell:
    command: |
      $windir = [Environment]::GetFolderPath('Windows')
      Start-Process -FilePath """$windir\AtlasModules\Scripts\fixStoreIssues.cmd""" -WindowStyle Hidden
    weight: 2
    wait: true
    exeDir: true
    onUpgrade: true
