---
title: Reverts changes
description: Reverts changes from past versions
privilege: TrustedInstaller
onUpgrade: true
actions:
  - !writeStatus: { status: "Reverting old changes" }
  - !run:
    exe: "%windir%\\AtlasModules\\Tools\\StoreFixer.exe"
    args: "silent"
    weight: 2
    wait: true
    exeDir: true
    onUpgrade: true
