---
title: Disable Game Bar
description: Disables XBOX Game Bar, which is known as a bloatware feature
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # Disable Game Bar
        @{ Path = 'HKCU\System\GameConfigStore'; Value = 'GameDVR_Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR'; Value = 'AppCaptureEnabled'; Data = '0'; Type = 'REG_DWORD' },
        # Disable Game Bar tips
        # Disable 'Open Xbox Game Bar using this button on a controller'
        @{ Path = 'HKCU\SOFTWARE\Microsoft\GameBar'; Value = 'GamePanelStartupTipIndex'; Data = '3'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\GameBar'; Value = 'ShowStartupPanel'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\GameBar'; Value = 'UseNexusForGameBarEnabled'; Data = '0'; Type = 'REG_DWORD' },
        # Disable Game Bar Presence Writer, required for GameBar
        @{ Path = 'HKLM\SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter'; Value = 'ActivationType'; Data = '0'; Type = 'REG_DWORD' },
        # Disable Windows Game Recording and Broadcasting
        # It automatically disables Game Bar
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\GameDVR'; Value = 'AllowGameDVR'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\ApplicationManagement\AllowGameDVR'; Value = 'value'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
