---
title: Disable Background Apps
description: Disables background apps so there's minimal resources used in the background
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications'; Value = 'GlobalUserDisabled'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search'; Value = 'BackgroundAppGlobalToggle'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
