---
title: Do Not Show Edge Tabs in Alt-Tab
description: Sets the 'Alt + Tab shows' option to 'Open windows only', meaning that individual Edge tabs won't be displayed, which would clutter the alt-tab interface
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'MultiTaskingAltTabFilter'; Data = '3'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
