---
title: Disable AutoRun
description: Disables AutoRun, also known as AutoPlay, for optimal QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers'; Value = 'DisableAutoplay'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\EventHandlersDefaultSelection\CameraAlternate'; Value = 'MSTakeNoAction'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\EventHandlersDefaultSelection\StorageOnArrival'; Value = 'MSTakeNoAction'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\UserChosenExecuteHandlers\CameraAlternate\ShowPicturesOnArrival'; Value = 'MSTakeNoAction'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\UserChosenExecuteHandlers\StorageOnArrival'; Value = 'MSTakeNoAction'; Data = ''; Type = 'REG_NONE' }
      )
    wait: true
    
    
