---
title: Disable Shared Experiences
description: Disables 'Shared Experiences', which is a way of sharing items between devices for privacy and QoL
actions:
  # https://www.elevenforum.com/t/turn-on-or-off-nearby-sharing-in-windows-11.2644/
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\CDP\SettingsPage'; Value = 'BluetoothLastDisabledNearShare'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\CDP'; Value = 'NearShareChannelUserAuthzPolicy'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\CDP'; Value = 'CdpSessionUserAuthzPolicy'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
