---
title: Disable Menu Hover Delay
description: Makes hovering over sub-menus in menus instant, instead of having a slight delay on hover
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'MenuShowDelay'; Data = '0'; Type = 'REG_SZ' }
      )
    wait: true
    
    
