---
title: Disable Recommendations in the Start Menu
description: Do not show recommendations for tips, shortcuts, new apps, and more in the Start Menu
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'Start_IrisRecommendations'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    builds: [ '>=22000' ]

  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'Start_AccountNotifications'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
