---
title: Set Unpinned Control Center Items
description: Disables unused control center items by default for QoL
actions:
  - !taskKill: {name: 'explorer'}

    # Windows 10
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'; Value = 'Microsoft.QuickAction.Connect'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'; Value = 'Microsoft.QuickAction.Location'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'; Value = 'Microsoft.QuickAction.ScreenClipping'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Control Panel\Quick Actions\Control Center\QuickActionsStateCapture'; Value = 'Toggles'; Data = 'Toggles,Microsoft.QuickAction.BlueLightReduction:false,Microsoft.QuickAction.AllSettings:false,Microsoft.QuickAction.Project:false'; Type = 'REG_SZ' }
      )
    wait: true
    builds: [ '<22000' ]

    # Windows 11
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'; Value = 'Microsoft.QuickAction.Cast'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'; Value = 'Microsoft.QuickAction.NearShare'; Data = ''; Type = 'REG_NONE' },
        @{ Path = 'HKCU\Control Panel\Quick Actions\Control Center\QuickActionsStateCapture'; Value = 'Toggles'; Data = 'Toggles,Microsoft.QuickAction.BlueLightReduction:false,Microsoft.QuickAction.Accessibility:false,Microsoft.QuickAction.ProjectL2:false'; Type = 'REG_SZ' }
      )
    wait: true
    builds: [ '>=22000' ]

  - !run: {exe: 'explorer.exe', runas: 'currentUser', wait: false}
