---
title: Show More Pins in Start
description: Shows more pins in the Start Menu, meaning less recommendations
builds: [ '>=22000' ]
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'Start_Layout'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
