---
title: Disable SMB Bandwidth Throttling
description: Disables SMB bandwidth throttling for improved performance
actions:
  - !powerShell:
    command: |
      # https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters'; Value = 'DisableBandwidthThrottling'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
