---
title: Restrict Anonymous Access
description: Restricts anonymous access to named pipes and shares to prevent unauthorized system access
actions:
  - !powerShell:
    command: |
      # https://www.stigviewer.com/stig/microsoft_windows_10/2022-04-08/finding/V-220932
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters'; Value = 'RestrictNullSessAccess'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
