---
title: Backup EBOS Services and Drivers
description: Backs up default EBOS services and drivers, after all the tweaks are finished
actions:
  - !powerShell:
    command: >-
      .\BACKUP.ps1 -FilePath """$([Environment]::GetFolderPath('Windows'))\AtlasModules\Other\ebosServices.reg"""
    wait: true
    exeDir: true
