version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "actions/*"
  - package-ecosystem: "pip"
    directory: "/.github"
    schedule:
      interval: "weekly"
    groups:
      ci-python:
        patterns:
          - "*"
