readme:
- '**/README.md'

actions:
- .github/workflows/**/*
- .github/labeler.yml

# Playbook

playbook:
- src/playbook/**/*

appx:
- src/playbook/Configuration/atlas/appx.yml

components:
- src/playbook/Configuration/atlas/components.yml

services:
- src/playbook/Configuration/atlas/services.yml

tweaks:
- src/playbook/Configuration/tweaks.yml
- src/playbook/Configuration/tweaks/**/*

desktop folder:
- src/playbook/Executables/AtlasDesktop/**/*
