readme:
- '**/README.md'

actions:
- .github/workflows/**/*
- .github/labeler.yml

# Playbook

playbook:
- playbook/**/*

appx:
- playbook/Configuration/atlas/appx.yml

components:
- playbook/Configuration/atlas/components.yml

services:
- playbook/Configuration/atlas/services.yml

tweaks:
- playbook/Configuration/tweaks.yml
- playbook/Configuration/tweaks/**/*

desktop folder:
- playbook/Executables/AtlasDesktop/**/*

build tooling:
- tools/**/*
- build.cmd
- build.sh

tests:
- tests/**/*
