readme:
- '**/README.md'

actions:
- .github/workflows/**/*
- .github/requirements-ci.txt
- .github/labeler.yml

# Playbook

playbook:
- playbook/**/*

appx:
- playbook/Executables/AtlasModules/Scripts/Phases/Invoke-AppxSupportPhase.ps1
- playbook/Executables/AtlasModules/Scripts/Modules/Atlas.Appx/**/*

components:
- playbook/Executables/AtlasModules/Scripts/Phases/Invoke-ComponentsPhase.ps1

services:
- playbook/Executables/AtlasModules/Scripts/Phases/Invoke-ServicesPhase.ps1
- playbook/Executables/AtlasModules/Scripts/Modules/Atlas.Services/**/*

tweaks:
- playbook/Configuration/custom.yml
- playbook/Executables/AtlasModules/Scripts/Phases/Invoke-TweaksPhase.ps1
- playbook/Executables/AtlasModules/Scripts/Modules/Atlas.Tweaks/**/*
- playbook/Executables/AtlasModules/Scripts/Tweaks/**/*

desktop folder:
- playbook/Executables/AtlasDesktop/**/*

build tooling:
- tools/**/*
- build.cmd
- build.sh

tests:
- tests/**/*
