---
title: Disallow Telemetry and Data Collection
description: Disallows telemetry and data collection to improve privacy
actions:
    # Stop DiagTrack service to add the changes
  - !service: {name: 'DiagTrack', operation: stop, ignoreErrors: true}
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack'; Value = 'ShowedToastAtLevel'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection'; Value = 'AllowTelemetry'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection'; Value = 'MaxTelemetryAllowed'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\Software\Policies\Microsoft\Windows\DataCollection'; Value = 'AllowTelemetry'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Policies\DataCollection'; Value = 'AllowTelemetry'; Data = '0'; Type = 'REG_DWORD' },
        # Misc
        @{ Path = 'HKLM\Software\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack\EventTranscriptKey'; Value = 'EnableEventTranscript'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\Software\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack\EventTranscriptKey'; Value = 'MiniTraceSlotEnabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\Software\Policies\Microsoft\Windows\DataCollection'; Value = 'AllowDeviceNameInTelemetry'; Data = '0'; Type = 'REG_DWORD' },
        # Disable & clear logger
        @{ Path = 'HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Diagtrack-Listener'; Value = 'Start'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
  - !cmd: {command: 'del "%ProgramData%\Microsoft\Diagnosis\ETLLogs\AutoLogger\DiagTrack*" "%ProgramData%\Microsoft\Diagnosis\ETLLogs\ShutdownLogger\DiagTrack*" > nul 2>&1'}
