---
title: Disable Input Telemetry
description: Disables text, ink and handwriting telemetry for privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\InputPersonalization'; Value = 'RestrictImplicitInkCollection'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\InputPersonalization'; Value = 'RestrictImplicitTextCollection'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\InputPersonalization\TrainedDataStore'; Value = 'HarvestContacts'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Personalization\Settings'; Value = 'AcceptedPrivacyPolicy'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\TabletPC'; Value = 'PreventHandwritingDataSharing'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\HandwritingErrorReports'; Value = 'PreventHandwritingErrorReports'; Data = '1'; Type = 'REG_DWORD' },
        # Disable typing insights
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Input\Settings'; Value = 'InsightsEnabled'; Data = '0'; Type = 'REG_DWORD' },
        # Disable improve inking and typing recognition
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Input\TIPC'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Input\TIPC'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
