---
title: Disable Key Management System Telemetry
description: Turns off KMS client online AVS validation, which prevents from sending data to Microsoft regardless of its activation state, for privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.SoftwareProtectionPlatform::NoAcquireGT
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform'; Value = 'NoGenTicket'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
