---
title: Add Registry Entries to 'New' Context Menu
description: Adds registry entries (.reg) to 'New' context menu
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCR\.reg\ShellNew'; Value = 'NullFile'; Data = ''; Type = 'REG_SZ' },
        @{ Path = 'HKCR\.reg\ShellNew'; Value = 'ItemName'; Data = '%windir%\regedit.exe,-309'; Type = 'REG_EXPAND_SZ' }
      )
    wait: true
