---
title: Add PowerShell Script to 'New' Context Menu
description: Adds PowerShell script (.ps1) to 'New' context menu
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCR\.ps1'; Value = ''; Data = 'Microsoft.PowerShellScript.1'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\.ps1\ShellNew'; Value = 'NullFile'; Data = ''; Type = 'REG_SZ' },
        @{ Path = 'HKCR\Microsoft.PowerShellScript.1'; Value = ''; Data = 'Windows PowerShell Script'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\Microsoft.PowerShellScript.1'; Value = 'FriendlyTypeName'; Data = 'Windows PowerShell Script'; Type = 'REG_SZ' }
      )
    wait: true
