---
title: Disable Use Check Boxes to Select Items
description: Disables check boxes in File Explorer to select items for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'AutoCheckSelect'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true

