---
title: Hide Recent Items
description: Hide recent items in Quick Access and other places for privacy and QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer'; Value = 'ShowFrequent'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer'; Value = 'ShowRecent'; Data = '0'; Type = 'REG_DWORD' },
        # Disable recent items and frequent places in File Explorer
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'Start_TrackDocs'; Data = '0'; Type = 'REG_DWORD' },
        # Clear history of recently opened documents on exit
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'; Value = 'ClearRecentDocsOnExit'; Data = '1'; Type = 'REG_DWORD' },
        # Do not keep history of recently opened documents
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'; Value = 'NoRecentDocsHistory'; Data = '1'; Type = 'REG_DWORD' },
        # Do not display or track items in jump lists from remote locations
        @{ Path = 'HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer'; Value = 'NoRemoteDestinations'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true

