---
title: Add Power Plan File Association
description: Adds a file association for .pow files, so you can simply double click on it and import it
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCR\powerscheme\DefaultIcon'; Value = ''; Data = '%windir%\System32\powercpl.dll,1'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\powerscheme\Shell\open\command'; Value = ''; Data = 'powercfg /import "%1"'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\.pow'; Value = ''; Data = 'powerscheme'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\.pow'; Value = 'FriendlyTypeName'; Data = 'Power Scheme'; Type = 'REG_SZ' }
      )
    wait: true
