---
title: Disable Internet File Association Service
description: Makes it so that Windows does not ask you if you want to get results from the web for an unknown file extension
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoInternetOpenWith'
    data: '1'
    type: REG_DWORD
