---
title: Open File Explorer to This PC
description: Configures File Explorer to open to This PC instead of Quick Access for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'LaunchTo'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true

