---
title: Remove Shortcut Text
description: Removes '- Shortcut' text appended onto the end of shortcuts for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\NamingTemplates'; Value = 'ShortcutNameTemplate'; Data = '"%s.lnk"'; Type = 'REG_SZ' }
      )
    wait: true

