---
title: Configure Explorer to Show All Files with File Extensions
description: Configures Explorer to show all files with file extensions such as system files, hidden files, etc. This is for QoL and also security.
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'Hidden'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'HideFileExt'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true

