---
title: Use Compact Mode
description: Sets compact mode in File Explorer
builds: [ '>=22000' ]
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'UseCompactMode'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true

