---
title: Disable Advertising ID
description: Disables Advertising ID for privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\Software\Policies\Microsoft\Windows\AdvertisingInfo'; Value = 'DisabledByGroupPolicy'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
