---
title: Configure App Permissions
description: Configures default app permissions in Settings for the optimal privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics'; Value = 'Value'; Data = 'Deny'; Type = 'REG_SZ' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location'; Value = 'Value'; Data = 'Deny'; Type = 'REG_SZ' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userAccountInformation'; Value = 'Value'; Data = 'Deny'; Type = 'REG_SZ' }
      )
    wait: true
