---
title: Disable App Launch Tracking
description: Prevents Windows from automatically tracking applications you use the most for improved privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # https://www.tenforums.com/tutorials/82967-turn-off-app-launch-tracking-windows-10-a.html
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'Start_TrackProgs'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
