---
title: Disable Windows Error Reporting
description: Disables Windows Error Reporting for privacy and QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.InternetCommunicationManagement::PCH_DoNotReport
        @{ Path = 'HKCU\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'; Value = 'Disabled'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting'; Value = 'DoReport'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'; Value = 'Disabled'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'; Value = 'DontShowUI'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting'; Value = 'ShowUI'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'; Value = 'LoggingDisabled'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'; Value = 'DontSendAdditionalData'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing'; Value = 'DisableWerReporting'; Data = '1'; Type = 'REG_DWORD' },
        # Do not send a Windows error report when a generic driver is installed on a device
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Settings'; Value = 'DisableSendGenericDriverNotFoundToWER'; Data = '1'; Type = 'REG_DWORD' },
        # Prevent Windows from sending an error report when a device driver requests additional software during installation
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Settings'; Value = 'DisableSendRequestAdditionalSoftwareToWER'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
