---
title: Disable Experimentation
description: Disallows Microsoft from using your computer as a test for certain features for privacy and stability
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\System\AllowExperimentation'; Value = 'Value'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
