---
title: Disallow Users to Be Non-local
description: For privacy and QoL, users are prevented from adding Microsoft accounts as user accounts instead of local accounts
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; Value = 'NoConnectedUser'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
