---
title: Disable OOBE Privacy Experience
description: Disables the OOBE (Out of Box Experience) privacy configuration that you might see on updates not to override current settings
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\OOBE'; Value = 'DisablePrivacyExperience'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
