---
title: Disable Activity Feed
description: Disables Activity Feed in Task View for privacy and QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System'; Value = 'EnableActivityFeed'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
