---
title: Disable Automatic Updates Of Speech Data
description: Disables auto-updates of speech data, as it is not commonly used, and it is a potential privacy concern or an overall annoyance
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Speech'; Value = 'AllowSpeechModelUpdate'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
