---
title: Disable Device Health Attestation Monitoring and Reporting
description: Disables Device Health Attestation Monitoring and Reporting on startup for privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\DeviceHealthAttestationService'; Value = 'EnableDeviceHealthAttestationService'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
