---
title: Disable Performance Track
description: Disables tracking of responsiveness events for privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.PerformancePerftrack::WdiScenarioExecutionPolicy
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}'; Value = 'ScenarioExecutionEnabled'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
