---
title: Disable Wallpaper Compression
description: Disables wallpaper compression so that your wallpaper is always in its full quality
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'JPEGImportQuality'; Data = '100'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
