---
title: Configure PowerShell
description: Configures PowerShell for the optimal privacy, performance and usability
privilege: TrustedInstaller
actions:
    # Disable PowerShell Core telemetry
  - !cmd: {command: 'setx POWERSHELL_TELEMETRY_OPTOUT 1'}
    # Set .ps1 file types to open with PowerShell by default
    # Batch scripts are not restricted and this measure can easily be bypassed by calling PowerShell within a batch script
  - !cmd: {command: 'ftype Microsoft.PowerShellScript.1="%windir%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -EP Unrestricted -File "%1" %*'}
  - !cmd:
    command: 'echo New-Item -Force -Path "Registry::HKEY_CLASSES_ROOT\Applications\powershell.exe\shell\open\command";New-ItemProperty -Path "Registry::HKEY_CLASSES_ROOT\Applications\powershell.exe\shell\open\command" -Name "(default)" -PropertyType String -Value ''"%windir%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -EP Unrestricted -File "%1" %*'' > script.ps1 & powershell -NoP -NoLogo -EP Unrestricted -File script.ps1'
    wait: true
    exeDir: true
  - !cmd:
    command: 'echo New-Item -Force -Path "Registry::HKEY_CLASSES_ROOT\ps1_auto_file\shell\open\command";New-ItemProperty -Path "Registry::HKEY_CLASSES_ROOT\ps1_auto_file\shell\open\command" -Name "(default)" -PropertyType String -Value ''"%windir%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -EP Unrestricted -File "%1" %*'' > script.ps1 & powershell -NoP -NoLogo -EP Unrestricted -File script.ps1'
    wait: true
    exeDir: true
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\OpenWithList'
    value: 'a'
    data: 'powershell.exe'
    type: REG_SZ
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\OpenWithList'
    value: 'MRUList'
    data: 'a'
    type: REG_SZ
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\OpenWithProgids'
    value: 'ps1_auto_file'
    data: ''
    type: REG_BINARY
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\UserChoice'
    value: 'ProgId'
    data: 'ps1_auto_file'
    type: REG_SZ

    # Set PowerShell execution policy to Unrestricted
    # Batch scripts are not restricted and this measure can easily be bypassed by calling PowerShell within a batch script
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell'
    value: 'ExecutionPolicy'
    operation: delete
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell'
    value: 'ExecutionPolicy'
    data: 'Unrestricted'
    type: REG_SZ
