---
title: Configure Start Menu
description: Configures the Start Menu's settings for QoL
actions:
    # Configure default Windows 11 pins
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\PolicyManager\current\device\Start'; Value = 'ConfigureStartPins'; Data = '{"pinnedList":[{"packagedAppId":"windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"},{"packagedAppId":"Microsoft.WindowsTerminal_8wekyb3d8bbwe!App"},{"desktopAppLink":"%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\File Explorer.lnk"},{"packagedAppId":"Microsoft.WindowsStore_8wekyb3d8bbwe!App"},{"packagedAppId":"Microsoft.GamingApp_8wekyb3d8bbwe!Microsoft.Xbox.App"},{"packagedAppId":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},{"packagedAppId":"Microsoft.WindowsNotepad_8wekyb3d8bbwe!App"},{"packagedAppId":"Microsoft.Paint_8wekyb3d8bbwe!App"},{"packagedAppId":"Microsoft.SecHealthUI_8wekyb3d8bbwe!SecHealthUI"}]}'; Type = 'REG_SZ' }
      )
    wait: true

    # Set start menu pins
  - !taskKill: {name: 'StartMenuExperienceHost', ignoreErrors: true}
  - !powerShell:
    command: '.\STARTMENU.ps1'
    exeDir: true
    wait: true
  - !appx: {operation: clearCache, name: 'Microsoft.Windows.StartMenuExperienceHost*'}

    # Remove frequent programs list from the Start Menu 
    # Hide "Most used" list from Start menu
    # Remove "Recently added" list from Start Menu
    # Remove Personalized Website Recommendations from the Recommended section in the Start Menu
    # https://www.elevenforum.com/t/add-or-remove-recommended-websites-on-start-menu-in-windows-11.10667/
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'; Value = 'NoStartMenuMFUprogramsList'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'; Value = 'ShowOrHideMostUsedApps'; Data = '2'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'; Value = 'HideRecentlyAddedApps'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'; Value = 'HideRecommendedPersonalizedSites'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
