---
title: Configure PowerShell
description: Configures PowerShell for the optimal privacy, performance and usability
privilege: TrustedInstaller
actions:
    # Disable PowerShell Core telemetry
  - !cmd: {command: 'setx POWERSHELL_TELEMETRY_OPTOUT 1'}

    # Set .ps1 file types to open with PowerShell by default
    # Pre-requisite to setting assosiations (FILEASSOC.cmd)
  - !cmd: {command: 'ftype Microsoft.PowerShellScript.1="%windir%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -EP Unrestricted -File "%1" %*'}

    # Set PowerShell execution policy to Unrestricted
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell'
    value: 'ExecutionPolicy'
    data: 'Unrestricted'
    type: REG_SZ
