---
title: Configure Windows Ink Workspace
description: Configures the Windows Ink Workspace to not be in the way, and have the best usability and privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\PenWorkspace'; Value = 'PenWorkspaceAppSuggestionsEnabled'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
