---
title: Disable Cross Device Resume
description: Disables the CrossDeviceResume process
builds: [ '>=22000' ]
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\CrossDeviceResume\Configuration'; Value = 'IsResumeAllowed'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\PolicyManager\default\Connectivity\DisableCrossDeviceResume'; Value = 'Value'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
    


