---
title: Disable Spell Checking
description: Disables spell checking for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'; Value = 'EnableAutocorrection'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'; Value = 'EnableDoubleTapSpace'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'; Value = 'EnablePredictionSpaceInsertion'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'; Value = 'EnableSpellchecking'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'; Value = 'EnableTextPrediction'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
