---
title: Disable Windows Feedback
description: Disables Windows Feedback for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Siuf\Rules'; Value = 'NumberOfSIUFInPeriod'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Siuf\Rules'; Value = 'PeriodInNanoSeconds'; Operation = 'delete' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection'; Value = 'DoNotShowFeedbackNotifications'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
