---
title: Disable Automatic Updates for Apps in Store
description: Disables automatic updates for apps in Store so that the user has more control
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate'; Value = 'AutoDownload'; Data = '2'; Type = 'REG_DWORD' }
      )
    wait: true
