---
title: Disable 'Notify About USB Issues'
description: Disables 'Notify me if there are issues connecting to USB devices' as this is prone to false positives, for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Shell\USB'; Value = 'NotifyOnUsbErrors'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Shell\USB'; Value = 'NotifyOnWeakCharger'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
