---
title: Disable Mouse Acceleration
description: Disables mouse acceleration (also called 'Enhance Pointer Precision') for 1:1 mouse movement, which is what most gamers would want
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Mouse'; Value = 'MouseSpeed'; Data = '0'; Type = 'REG_SZ' },
        @{ Path = 'HKCU\Control Panel\Mouse'; Value = 'MouseThreshold1'; Data = '0'; Type = 'REG_SZ' },
        @{ Path = 'HKCU\Control Panel\Mouse'; Value = 'MouseThreshold2'; Data = '0'; Type = 'REG_SZ' }
      )
    wait: true
    
    
