---
title: Disable Settings Tips
description: Disables Settings tips for QoL, as most of the time, they only get in the way
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\Settings\AllowOnlineTips'; Value = 'value'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'; Value = 'AllowOnlineTips'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
