---
title: Hide Disabled and Disconnected Devices in Sounds Panel
description: Hides disabled and disconnected devices in the sounds panel (mmsys.cpl) for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Multimedia\Audio\DeviceCpl'; Value = 'ShowDisconnectedDevices'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Multimedia\Audio\DeviceCpl'; Value = 'ShowHiddenDevices'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
