---
title: Show All Tasks in Control Panel
description: Shows 'All Tasks' in Control Panel (God Mode), so that people can easily access all settings for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCR\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'; Value = ''; Data = 'All Tasks'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'; Value = 'InfoTip'; Data = 'View list of all Control Panel tasks'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'; Value = 'System.ControlPanel.Category'; Data = '5'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}\DefaultIcon'; Value = ''; Data = '%windir%\System32\imageres.dll,-27'; Type = 'REG_SZ' },
        @{ Path = 'HKCR\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}\Shell\Open\Command'; Value = ''; Data = 'explorer.exe shell:::{ED7BA470-8E54-465E-825C-99712043E01C}'; Type = 'REG_SZ' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\NameSpace\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'; Value = ''; Data = 'All Tasks'; Type = 'REG_SZ' }
      )
    wait: true
