---
title: Configure Visual Effects
description: Configures the visual effects in Windows for the optimal responsiveness, performance and QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'FontSmoothing'; Data = '2'; Type = 'REG_SZ' },
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'UserPreferencesMask'; Data = '9012038010000000'; Type = 'REG_BINARY' },
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'DragFullWindows'; Data = '1'; Type = 'REG_SZ' },
        @{ Path = 'HKCU\Control Panel\Desktop\WindowMetrics'; Value = 'MinAnimate'; Data = '0'; Type = 'REG_SZ' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'ListviewAlphaSelect'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'IconsOnly'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'TaskbarAnimations'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'ListviewShadow'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects'; Value = 'VisualFXSetting'; Data = '3'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\DWM'; Value = 'EnableAeroPeek'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\DWM'; Value = 'AlwaysHibernateThumbnails'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
