---
title: Add newUsers.cmd script
description: Adds the newUsers.ps1 script to RunOnce, which applies any tweaks that are dynamically generated on new user creation
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'; Value = 'RunScript'; Data = 'powershell -EP Bypass -NoP & """$([Environment]::GetFolderPath(''Windows''))\AtlasModules\Scripts\newUsers.ps1"""'; Type = 'REG_SZ' }
      )
    wait: true