---
title: Add newUsers.cmd script
description: Adds the newUsers.cmd script to RunOnce, which applies any tweaks that are dynamically generated on new user creation
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
    value: 'RunScript'
    data: |
      cmd /d /c ""%windir%\AtlasModules\Scripts\newUsers.cmd""
    type: REG_SZ
