---
title: Configure OEM Information
description: Configures OEM information to contain the Atlas version and the Atlas Discord server
actions:
  - !powerShell:
    command: |
      $version = 'AtlasVersionUndefined'

      Write-Output 'Setting boot entry name...'
      bcdedit /set description """AtlasOS $(('10', '11')[[int]([System.Environment]::OSVersion.Version.Build -ge 22000)]) $version"""

      Write-Output 'Setting other versioned OEM information...'
      $reportedVer = """Atlas Playbook $version"""
      # Shows in Settings
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation' -Name 'Model' -Value $reportedVer -Force
      # Shows in winver
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name 'RegisteredOrganization' -Value $reportedVer -Force
    wait: true
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'; Value = 'Manufacturer'; Data = 'Atlas Team'; Type = 'REG_SZ' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'; Value = 'SupportURL'; Data = 'https://discord.atlasos.net'; Type = 'REG_SZ' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'; Value = 'SupportPhone'; Data = 'https://github.com/Atlas-OS/Atlas'; Type = 'REG_SZ' }
      )
    wait: true
