---
title: Create Shortcuts
description: Creates shortcuts for the desktop and more
privilege: TrustedInstaller
actions:
  - !powerShell:
    command: '.\SHORTCUTS.ps1'
    exeDir: true
    wait: true
