---
title: Delete Windows-version Specific Tweaks
description: Deletes Windows 10 or Windows 11-only tweaks in the Atlas folder, depending on the Windows version
privilege: TrustedInstaller
actions:
    # Delete Windows 11-only tweaks
  - !file: {path: '%windir%\AtlasDesktop\3. Configuration\Background Apps', builds: [ '!>=22000' ]}
  - !file: {path: '%windir%\AtlasDesktop\3. Configuration\Power\Timer Resolution', builds: [ '!>=22000' ]}
  - !file: {path: '%windir%\AtlasDesktop\4. Optional Tweaks\File Explorer Customization\Compact View', builds: [ '!>=22000' ]}
  - !file: {path: '%windir%\AtlasDesktop\4. Optional Tweaks\File Explorer Customization\Gallery', builds: [ '!>=22000' ]}
  - !file: {path: '%windir%\AtlasDesktop\4. Optional Tweaks\Windows 11 Context Menu', builds: [ '!>=22000' ]}
  - !file: {path: '%windir%\AtlasModules\Tools\TimerResolution.exe', builds: [ '!>=22000' ]}

    # Delete Windows 10-only tweaks
  - !file: {path: '%windir%\AtlasDesktop\4. Optional Tweaks\Volume Flyout', builds: [ '>=22000' ], ignoreErrors: true}
