---
title: Disable Remote Assistance
description: As Remote Assistance is an unused and a potential vulnerable feature, it is disabled
actions:
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Remote Assistance'
    value: 'fAllowFullControl'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Remote Assistance'
    value: 'fAllowToGetHelp'
    data: '0'
    type: REG_DWORD
  # the remote assistance firewall group is localized, so we target the invariant resource identifier instead
  - !run:
    exe: 'powershell'
    args: >-
      -NoProfile -ExecutionPolicy Bypass -Command "$group = '@FirewallAPI.dll,-33002';
      if (Get-Command -Name Disable-NetFirewallRule -ErrorAction SilentlyContinue) {
        $rules = Get-NetFirewallRule -Group $group -ErrorAction SilentlyContinue;
        if ($rules) {
          $null = $rules | Disable-NetFirewallRule -ErrorAction SilentlyContinue
        }
      }"
    ignoreErrors: true
