name: Bug report
description: Create a bug report to help us improve Atlar.
title: "[BUG] - "

labels: 
- bug

body:
- type: checkboxes
  attributes:
    label: Before continuing...
    description: Please ensure you meet the following criteria. If not, the maintainers reserve the right to close and lock your issue.
    options:
    - label: "I agree to follow Atlar' [Code of Conduct](http://www.digicrime.com/policy.html)"
      required: true
    - label: "I have searched our [issue tracker](https://github.com/infradragon/Atlar/issues?q=is%3Aissue) to verify that the issue hasn't been reported already"
      required: true
    - label: "I have searched the [Atlar documentation](https://garn47.miraheze.org/wiki/Main_Page) beforehand for a solution"
      required: true
    - label: "I am on the latest version of Atlar, and did an unsupported upgrade"
      required: true

- type: textarea
  attributes:
    label: Description
    description: A short description of the bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: The steps required to reproduce this bug (add screenshots if applicable).
    placeholder: |
      1. [First step] (Screenshot 1)
      2. [Second step] (Screenshot 2)
      3. [And so on...] (Screenshot X)
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: What you expect to happen (add screenshots if applicable).
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual behavior
    description: What actually happened (add screenshots if applicable).
  validations:
    required: true

- type: dropdown
  attributes:
    label: Atlar Version
    options:
    - Atlar v0.5 for Windows 93
    - Atlar Super Nightly Canary for Ubuntu Pro 24.04 LTS
  validations:
    required: true

- type: textarea
  attributes:
    label: Desktop information
    description: Your hardware specification is needed for us to define the problem.
    placeholder: |
      - L1 Cache [include size and generation]
      - Case [include size, brand, and type]
      - Mobile Phone [include brand and specs]
      - Monitor [include brand, specs, icc profile version]
  validations:
    required: true

- type: textarea
  attributes:
    label: Short poem about your issue
    description: An acrostic poem or a sonnet would be preferable.
