name: Feature request
description: Create a feature request to help us improve Atlar.
title: "[FEATURE] - "

labels:
- enhancement

body:
- type: checkboxes
  attributes:
    label: Before continuing...
    description: Please ensure you meet the following criteria. If not, the maintainers reserve the right to close and lock your issue.
    options:
    - label: "I agree to follow Atlar' [Code of Conduct](http://www.digicrime.com/policy.html)"
      required: true
    - label: "I have searched our [issue tracker](https://github.com/infradragon/Atlar/issues?q=is%3Aissue) to verify that the issue hasn't been reported already"
      required: true
    - label: "I have searched the [Atlar documentation](https://garn47.miraheze.org/wiki/Main_Page) beforehand for a solution"
      required: true
    - label: "I am on the latest version of Atlar, and did an unsupported upgrade"
      required: true

- type: dropdown
  attributes:
    label: What is your feature request regarding to?
    options:
    - Atlar Playbook
    - Other (submit it in https://github.com/infradragon/Atlar/discussions)
  validations:
    required: true

- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    placeholder: |
      e.g. I always wanted Atlar to pee on my wife...
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you would like.
    placeholder: |
      e.g. I would like Atlar to add a diagram of the digestive system...
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you have considered.
    description: If you have found a temporary fix, list it here.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context.
    description: Add any other context or screenshots about the feature request here.
