name: Feature request
description: Create a feature request to help us improve Atlas.
labels: enhancement
title: "[FEATURE] - "
body:
  - type: markdown
    attributes:
      value: |
       Before submitting an feature request, please ensure you have completed the following steps:
       - The request you submit is related to the Atlas Playbook. If not, request it in our [forum](https://forum.atlasos.net/t/general)
       - Searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
       - Confirmed that your issue is not a support request
       - Confirmed that your idea is not already in the latest version of Atlas

       Please note, by submitting an issue, you acknowledge that if the above steps have not been followed, the maintainers reserve the right to close and lock your issue without further response.
  - type: dropdown
    attributes:
      label: What is your feature request regarding to?
      options:
        - Atlas Playbook
        - Other (submit it in https://forum.atlasos.net)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: |
        e.g. I always wanted Atlas to...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you would like.
      placeholder: |
        e.g. I would like Atlas to add...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you have considered.
      description: If you have found a temporary fix, list it here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
    validations:
