[Theme]
DisplayName=ebos-liquid-glass
ThemeId={B8AB47FF-2721-46C8-9871-AA5F7CC35ADA}

[Control Panel\Desktop]
Wallpaper=%windir%\AtlasModules\Wallpapers\ebos-liquid-glass.png
Pattern=
MultimonBackgrounds=0
PicturePosition=4
WindowsSpotlight=0

[Control Panel\Cursors]
AppStarting=%SystemRoot%\cursors\aero_working.ani
Arrow=%SystemRoot%\cursors\aero_arrow.cur
Hand=%SystemRoot%\cursors\aero_link.cur
Help=%SystemRoot%\cursors\aero_helpsel.cur
No=%SystemRoot%\cursors\aero_unavail.cur
NWPen=%SystemRoot%\cursors\aero_pen.cur
SizeAll=%SystemRoot%\cursors\aero_move.cur
SizeNESW=%SystemRoot%\cursors\aero_nesw.cur
SizeNS=%SystemRoot%\cursors\aero_ns.cur
SizeNWSE=%SystemRoot%\cursors\aero_nwse.cur
SizeWE=%SystemRoot%\cursors\aero_ew.cur
UpArrow=%SystemRoot%\cursors\aero_up.cur
Wait=%SystemRoot%\cursors\aero_busy.ani
DefaultValue=Windows Default
Crosshair=
IBeam=
[Sounds]
SchemeName=No Sounds

[VisualStyles]
Path=%windir%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XFF4CC9F0
SystemMode=Dark
AppMode=Dark
