---
title: Restrict Windows Insider
description: Forcefully restricts Windows Insider from being enabled to prevent extra data collection, tweaks being reverted and general instability.
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # Disable Windows Insider 
        # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.WindowsUpdate::ManagePreviewBuilds
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'; Value = 'ManagePreviewBuilds'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'; Value = 'ManagePreviewBuildsPolicyValue'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds'; Value = 'AllowBuildPreview'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds'; Value = 'EnableConfigFlighting'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds'; Value = 'EnableExperimentation'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\WindowsSelfHost\UI\Visibility'; Value = 'HideInsiderPage'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
