---
title: Disable WU Auto-Reboot
description: Disables Windows Update from automatically restarting your computer when there's pending updates.
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # Make WU not wake up your computer to install updates
        # Seems to be legacy on Windows 11
        # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.WindowsUpdate::AUPowerManagement_Title
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'; Value = 'AUPowerManagement'; Data = '0'; Type = 'REG_DWORD' },
        # Don't reboot with logged in users
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU'; Value = 'NoAutoRebootWithLoggedOnUsers'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
