---
title: Disable MSRT telemetry
description: Disables MSRT's (Malicious Software Removal Tool) telemetry features
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # Disable MSRT telemetry
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\MRT'; Value = 'DontReportInfectionInformation'; Type = 'REG_DWORD'; Data = '1' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\RemovalTools\MpGears'; Value = 'HeartbeatTrackingIndex'; Type = 'REG_DWORD'; Data = '0' },
        @{ Path = 'HKLM\SOFTWARE\Microsoft\RemovalTools\MpGears'; Value = 'SpyNetReportingLocation'; Type = 'REG_MULTI_SZ'; Data = '' }
      )
    wait: true
