---
title: Set File Associations
description: Sets file associations for the user-selected web browser and other apps
actions:
  - !run:
    exe: '%windir%\AtlasModules\Scripts\Set-FileAssociationsLauncher.cmd'
    option: '!uninstall-edge'
  - !run:
    exe: '%windir%\AtlasModules\Scripts\Set-FileAssociationsLauncher.cmd'
    args: '"Brave"'
    option: 'browser-brave'
  - !run:
    exe: '%windir%\AtlasModules\Scripts\Set-FileAssociationsLauncher.cmd'
    args: '"LibreWolf"'
    option: 'browser-librewolf'
  - !run:
    exe: '%windir%\AtlasModules\Scripts\Set-FileAssociationsLauncher.cmd'
    args: '"Firefox"'
    option: 'browser-firefox'
  - !run:
    exe: '%windir%\AtlasModules\Scripts\Set-FileAssociationsLauncher.cmd'
    args: '"Google Chrome"'
    option: 'browser-chrome'
