---
title: Set Profile Pictures
description: Sets the default Atlas profile pictures
onUpgrade: false
actions:
  - !powerShell:
    command: '& ".\AtlasModules\Scripts\Internal\ProfilePictures.ps1"'
    exeDir: true
    wait: true
