---
title: Backup Atlas Services and Drivers
description: Backs up default Atlas services and drivers, after all the tweaks are finished
actions:
  - !powerShell:
    command: |
      & (Join-Path ([Environment]::GetFolderPath('Windows')) 'AtlasModules\initPowerShell.ps1')
      Import-Module Atlas.Services
      Export-AtlasServicesBackup -FilePath (Join-Path ([Environment]::GetFolderPath('Windows')) 'AtlasModules\Other\atlasServices.reg')
    wait: true
