---
title: Components
description: Removes certain Windows components
actions:
    # Remove Security Center startup item
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'SecurityHealth', operation: delete}

    # Disable Smart App Control
    # Causes slow app loading issues and sends data to Microsoft
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\CI\Policy'
    value: 'VerifiedAndReputablePolicyState'
    data: '0'
    type: REG_DWORD

    # Microsoft Edge
  - !writeStatus: {status: 'Removing Microsoft Edge', option: 'uninstall-edge'}
  - !powerShell:
    command: '& """.\AtlarModules\Scripts\ScriptWrappers\RemoveEdge.ps1""" -UninstallEdge -RemoveEdgeData -KeepAppX -NonInteractive'
    runas: currentUserElevated
    option: 'uninstall-edge'
    wait: true
    exeDir: true
    # AppX uninstallation in the script seems to fail, therefore it's not used and AME Wizard is used instead
    # Note that AppX Edge is removed from the latest builds of Windows, but people could be running a non-updated version
  - !appx: {name: 'Microsoft.MicrosoftEdge_8wekyb3d8bbwe', type: family, option: 'uninstall-edge'}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe', operation: add, option: 'uninstall-edge'}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge_8wekyb3d8bbwe', operation: add, option: 'uninstall-edge'}

    # OneDrive
    # The actual OneDrive setup in Windows is stripped at a component-level in the miscellaneous package
  - !writeStatus: {status: 'Removing OneDrive'}
  - !run: {exeDir: true, exe: 'ONED.cmd'}

    # Windows components and Telemetry
  - !writeStatus: {status: 'Removing components'}
  - !powerShell:
    command: 'echo balls'
    option: 'defender-disable'
    wait: true
    exeDir: true
  - !powerShell:
    command: 'echo "balls 2"'
    option: 'defender-enable'
    wait: true
    exeDir: true
