---
title: Show Command Prompt on Win+X
description: Shows Command Prompt instead of PowerShell on Windows + X, as it is what most users are familiar with
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'DontUsePowerShellOnWinX'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
