---
title: Configure Taskbar Pins
description: Configures taskbar pins for QoL, puts the browser first (if there is one) and Explorer next
onUpgrade: false
actions:
    # PowerShell commands used:
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "FavoritesResolve").FavoritesResolve) -replace '-' | clip
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "Favorites").Favorites) -replace '-' | clip
    # Config pins
  - !registryKey:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
  - !registryKey:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
    operation: add
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'; Value = 'FavoritesVersion'; Data = '3'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'; Value = 'MailPin'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'; Value = 'CopilotPWAPin'; Data = '0'; Type = 'REG_DWORD' }
        # Not sure what this does
        # @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'; Value = 'TFLPin'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true

# Sets a temporary value for taskbar pins after oobe
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\AtlasOS\SetupOptions'; Value = 'browser'; Data = 'Brave'; Type = 'REG_SZ' }
      )
    option: 'browser-brave'
    wait: true
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\AtlasOS\SetupOptions'; Value = 'browser'; Data = 'Firefox'; Type = 'REG_SZ' }
      )
    option: 'browser-firefox'
    wait: true
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\AtlasOS\SetupOptions'; Value = 'browser'; Data = 'Google Chrome'; Type = 'REG_SZ' }
      )
    option: 'browser-chrome'
    wait: true
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\AtlasOS\SetupOptions'; Value = 'browser'; Data = 'LibreWolf'; Type = 'REG_SZ' }
      )
    option: 'browser-librewolf'
    wait: true
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\AtlasOS\SetupOptions'; Value = 'browser'; Data = ''; Type = 'REG_SZ' }
      )
    option: 'browser-librewolf'
    wait: true

  - !powerShell:
    command: '.\TASKBARPINS.ps1'
    option: '!install-another-browser'
    exeDir: true
    oobe: false
    wait: true
  - !powerShell:
    command: ".\\TASKBARPINS.ps1 'Brave'"
    option: 'browser-brave'
    exeDir: true
    oobe: false
    wait: true
  - !powerShell:
    command: ".\\TASKBARPINS.ps1 'Firefox'"
    option: 'browser-firefox'
    exeDir: true
    oobe: false
    wait: true
  - !powerShell:
    command: ".\\TASKBARPINS.ps1 'Google Chrome'"
    option: 'browser-chrome'
    exeDir: true
    oobe: false
    wait: true
  - !powerShell:
    command: ".\\TASKBARPINS.ps1 'LibreWolf'"
    option: 'browser-librewolf'
    exeDir: true
    oobe: false
    wait: true