---
title: Disable Microsoft Copilot
description: Disables Microsoft Copilot as it depends on Edge, as well it collecting data and not being used by most users
builds: [ '>=22000' ]
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # Doesn't work with HKLM
        @{ Path = 'HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot'; Value = 'TurnOffWindowsCopilot'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
