---
title: Disable News and Interests
description: Disables News and Interests on the taskbar for privacy (lots of third party connections) and QoL
actions:
  - !taskKill: {name: 'explorer'}

  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds'; Value = 'EnableFeeds'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Dsh'; Value = 'AllowNewsAndInterests'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true

  - !run: {exe: 'explorer.exe', runas: 'currentUser', wait: false}
