---
title: Disable Windows Chat
description: Disables Windows Chat as it's not commonly used
builds: [ '>=22000' ]
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Chat'; Value = 'ChatIcon'; Data = '3'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'TaskbarMn'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
