---
title: Disable Cloud Optimized Content on Taskbar
description: Disables cloud optimized content in the taskbar for QoL, which pins items dependent on things like having linked phone or Xbox Live - seems to break Windows Spotlight
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent'; Value = 'DisableCloudOptimizedContent'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
