---
title: Hide 'Meet Now' on Taskbar
description: Hides 'Meet Now' on the taskbar for QoL and privacy (as it is an online feature)
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'; Value = 'HideSCAMeetNow'; Data = '1'; Type = 'REG_DWORD' }
      )
    wait: true
