---
title: Set Taskbar to Align Left
description: Sets taskbar to align left instead of centered
builds: [ '>=22000' ]
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'; Value = 'TaskbarAl'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
