---
title: Decrease Shutdown Time
description: Makes it so that Windows is less tolerable to hung apps, and tries to kill them as fast as possible on shutdown
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'HungAppTimeout'; Data = '2000'; Type = 'REG_SZ' },
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'WaitToKillAppTimeOut'; Data = '2000'; Type = 'REG_SZ' },
        @{ Path = 'HKLM\SYSTEM\CurrentControlSet\Control'; Value = 'WaitToKillServiceTimeout'; Data = '2000'; Type = 'REG_SZ' }
      )
    wait: true
