---
title: Disable Startup Delay
description: Disables the startup delay of startup applications
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Serialize'; Value = 'StartupDelayInMSec'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
