---
title: Force Close Applications On Session End
description: Forcefully closes all applications on restart, shut down, or sign out of Windows, instead of prompting the user to save everything first
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Desktop'; Value = 'AutoEndTasks'; Data = '1'; Type = 'REG_SZ' }
      )
    wait: true
    
    
