---
title: Reverts changes
description: Reverts changes from past versions
privilege: TrustedInstaller
onUpgrade: true
actions:
  - !writeStatus: { status: "Reverting old changes" }
  - !powerShell:
    command: '& (Join-Path ([Environment]::GetFolderPath(''Windows'')) ''AtlasModules\Scripts\Invoke-AtlasInstall.ps1'') -Phase Revert'
    weight: 2
    wait: true
    onUpgrade: true
    handleExitCodes: { "!0": halt }
