---
title: Add Theme
description: Adds and sets the Atlas themes by default
actions:
    #Apply theme file and set recent themes
  - !powerShell:
    command: |
      .\AtlasModules\initPowerShell.ps1
      Set-ThemeMRU
    wait: true
    onUpgrade: true
    oobe: true
    exeDir: true
    runas: currentUserElevated
    
  - !powerShell:
    command: |
      .\AtlasModules\initPowerShell.ps1
      Set-Theme -Path """$([Environment]::GetFolderPath('Windows'))\Resources\Themes\atlas-v0.5.x-dark.theme"""
      Set-ThemeMRU
    wait: true
    onUpgrade: false
    exeDir: true
    runas: currentUserElevated

    # Applies Atlas lockscreen background & wallpaper 
    # Also disables fun facts, tips, tricks, and more on lockscreen - only on Enterprise/Education
    # Set Atlas theme as default for new users
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization'; Value = 'LockScreenOverlaysDisabled'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'; Value = 'RotatingLockScreenEnabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKU\AME_UserHive_Default\Software\Policies\Microsoft\Windows\Personalization'; Value = 'ThemeFile'; Data = '%windir%\Resources\Themes\atlas-v0.5.x-dark.theme'; Type = 'REG_SZ' }
      )
    wait: true
  - !powerShell:
    command: |
      foreach ($userKey in (Get-ChildItem "HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\Creative").PsPath) {
          Set-ItemProperty -Path $userKey -Name 'RotatingLockScreenEnabled' -Type DWORD -Value 0 -Force
      }
    exeDir: true
    wait: true
    onUpgrade: false
  - !powerShell:
    command: |
      .\AtlasModules\initPowerShell.ps1
      Set-LockscreenImage
    exeDir: true
    wait: true
    runas: currentUserElevated
    onUpgrade: false
    
    
