---
title: Change the Tooltip Color to Blue
description: Changes the tooltip color to blue
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Colors'; Value = 'InfoWindow'; Data = '246 253 255'; Type = 'REG_SZ' }
      )
    wait: true
    
    
