---
title: Disallow Themes to Change Certain Personalized Features
description: Disallows themes to change certain personalized features, as most of the time people only really apply themes for wallpapers or Windows style skins (custom themes)
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes'; Value = 'ThemeChangesMousePointers'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes'; Value = 'ThemeChangesDesktopIcons'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
    
    
