---
title: Disable Ease of Access Sounds
description: Disable Ease Of Access sounds on activation or sound warnings, like the infamous sticky keys sound, for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Accessibility'; Value = 'Warning Sounds'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Control Panel\Accessibility'; Value = 'Sound on Activation'; Data = '0'; Type = 'REG_DWORD' },
        # Disable visual warning for sounds in ease of access
        @{ Path = 'HKCU\Control Panel\Accessibility\SoundSentry'; Value = 'WindowsEffect'; Data = '0'; Type = 'REG_SZ' }
      )
    wait: true
