---
title: Disable 'Always Read and Scan This Section'
description: Disables 'Always Read and Scan This Section' in Control Panel for QoL
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Ease of Access'; Value = 'selfscan'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Ease of Access'; Value = 'selfvoice'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
