---
title: Disable Commonly Annoying Features and Shortcuts
description: Disables commonly annoying features such as pressing shift 5 times for sticky keys.
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKCU\Control Panel\Accessibility\HighContrast'; Value = 'Flags'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Control Panel\Accessibility\Keyboard Response'; Value = 'Flags'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Control Panel\Accessibility\MouseKeys'; Value = 'Flags'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Control Panel\Accessibility\StickyKeys'; Value = 'Flags'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Control Panel\Accessibility\ToggleKeys'; Value = 'Flags'; Data = '0'; Type = 'REG_DWORD' },
        # Disable language bar shortcuts
        @{ Path = 'HKCU\Keyboard Layout\Toggle'; Value = 'Layout Hotkey'; Data = '3'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Keyboard Layout\Toggle'; Value = 'Language Hotkey'; Data = '3'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\Keyboard Layout\Toggle'; Value = 'Hotkey'; Data = '3'; Type = 'REG_DWORD' },
        # Disable Narrator shortcut
        @{ Path = 'HKCU\Software\Microsoft\Narrator\NoRoam'; Value = 'WinEnterLaunchEnabled'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
  # Disable language bar shortcuts
  - !registryKey:
    path: 'HKCU\Control Panel\Input Method\Hot Keys\00000104'
