# Public QOL module surface.
# Domain implementations live under .\Domain so Atlas can keep stable command names
# while avoiding a single monolithic maintenance file.
$domainRoot = Join-Path -Path $PSScriptRoot -ChildPath 'Domain'

foreach ($domainModule in @(
    'Accessibility.ps1'
    'Appearance.ps1'
    'Explorer.ps1'
    'Shell.ps1'
    'StartupShutdown.ps1'
    'SystemShortcuts.ps1'
    'Taskbar.ps1'
)) {
    $domainPath = Join-Path -Path $domainRoot -ChildPath $domainModule
    if (-not (Test-Path -LiteralPath $domainPath -PathType Leaf)) {
        throw "Required QOL domain module '$domainPath' is missing."
    }

    . $domainPath
}

Export-ModuleMember -Function @(
    'Add-EndTaskToTaskbar'
    'Add-NetworkSharingShortcut'
    'Disable-AccessibilityToolShortcut'
    'Disable-AeroShake'
    'Disable-AnnoyingFeaturesAndShortcuts'
    'Disable-AutoRun'
    'Disable-AutomaticStoreAppArchiving'
    'Disable-DynamicLighting'
    'Disable-EaseOfAccessSounds'
    'Disable-LowDiskSpaceChecks'
    'Disable-MenuHoverDelay'
    'Disable-MicrosoftCopilot'
    'Disable-MouseAcceleration'
    'Disable-NetworkNavigationPaneInExplorer'
    'Disable-ReadAndScan'
    'Disable-ReduceSoundsWhileInCall'
    'Disable-ScreenCaptureHotkey'
    'Disable-SearchingForInvalidShortcuts'
    'Disable-SharedExperiences'
    'Disable-ShowDesktopPeek'
    'Disable-ShowEdgeTabsInAltTab'
    'Disable-SpellChecking'
    'Disable-StartMenuRecommendations'
    'Disable-StartupDelay'
    'Disable-TaskViewOnTaskbar'
    'Disable-ThemeChangesToPersonalizedFeatures'
    'Disable-TouchVisualFeedback'
    'Disable-UnnecessaryTouchKeyboardSettings'
    'Disable-UseCheckBoxesToSelectItems'
    'Disable-WallpaperCompression'
    'Disable-WindowsChat'
    'Disable-WindowsFeedback'
    'Disable-WindowsSpotlight'
    'Enable-CompactMode'
    'Hide-DisabledAndDisconnectedDevicesInSoundsPanel'
    'Hide-GalleryInFileExplorer'
    'Hide-OfficeFilesInQuickAccess'
    'Hide-RecentItems'
    'Hide-TabletMode'
    'Remove-ExtractFromContextMenu'
    'Remove-PreviousVersionsFromExplorer'
    'Remove-PrintingFromContextMenus'
    'Remove-ShortcutText'
    'Restore-OldContextMenu'
    'Set-AtlasTheme'
    'Set-BootConfiguration'
    'Set-CloseApplicationsOnSessionEnd'
    'Set-FileExplorerToThisPC'
    'Set-MouseHoverTimeForItemInfo'
    'Set-SendToContextMenu'
    'Set-ShutdownTime'
    'Set-StartMenu'
    'Set-TaskbarAlignLeft'
    'Set-TooltipColorBlue'
    'Set-UnpinnedControlCenterItems'
    'Set-VisualEffects'
    'Set-WindowsInkWorkspace'
    'Show-AllFilesWithExtensions'
    'Show-CommandPromptOnWinX'
    'Show-FullContextMenuOnItems'
    'Show-MoreDetailsOnTransfers'
    'Show-MorePinsInStartMenu'
)
