---
title: Disable Settings Sync
description: Disables Settings Sync (labeled as 'Windows Backup' in Windows 10) for QoL and privacy
actions:
  - !powerShell:
    command: |
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        # Policies don't disable the toggles in the UI, doesn't seem like much can be done about it
        # Whole Settings page is hidden anyways
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'; Value = 'DisableSettingSync'; Data = '2'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'; Value = 'DisableSettingSyncUserOverride'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'; Value = 'DisableSyncOnPaidNetwork'; Data = '1'; Type = 'REG_DWORD' },
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'; Value = 'DisableWindowsSettingSync'; Data = '2'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Personalization'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\BrowserSettings'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Credentials'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Accessibility'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Windows'; Value = 'Enabled'; Data = '0'; Type = 'REG_DWORD' },
        @{ Path = 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync'; Value = 'SyncPolicy'; Data = '5'; Type = 'REG_DWORD' }
      )
    wait: true
    
