---
title: Applies Atlar's Network Settings
description: Applies Atlar's optimised network settings
actions:
  - !cmd:
    command: '"AtlarDesktop\8. Troubleshooting\Network\Reset Network to Atlar Default.cmd" /silent'
    exeDir: true
    wait: true
