---
title: Disable LLMNR Protocol
description: Disable Link-Local Multicast Name Resolution (LLMNR) protocol as it is vulnerable and has been replaced by DNS
actions:
  - !powerShell:
    command: |
      # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.DNSClient::Turn_Off_Multicast
      . "$env:windir\AtlasModules\Scripts\regHelp.ps1" -RegistryObjects @(
        @{ Path = 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient'; Value = 'EnableMulticast'; Data = '0'; Type = 'REG_DWORD' }
      )
    wait: true
